### PR TITLE
[chore] Add multiple source docs

### PR DESCRIPTION
**Pull request by colmazia**
## Implementation details
- Do 1
- Do 2

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the GitHub PR explorer)

### CODE REVIEW

**Comment by RogerKSI** [comment]
@colmazia  please fix test-stable as well.

**Review by warittornc — CHANGES_REQUESTED** [review]
please follow the same format as bothan-api. 
https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md#appendix-a-full-conventions-text

**Comment by colmazia** [comment]
> please follow the same format as bothan-api. https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md#appendix-a-full-conventions-text

Could you give me an example of what went wrong here, and how to correct it?

**Comment by colmazia** [comment]
bc I try to do the same as the bothan-binance

**Review by RogerKSI — APPROVED** [review]

**Pull request merged**
