### PR TITLE
[feat] Add Uniswap

### PR DESCRIPTION
**Pull request by warittornc**
## Implementation details
- Do 1
- Do 2

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the GitHub PR explorer)

### CODE REVIEW

**Review by RogerKSI — APPROVED** [review]

**Review by RogerKSI — APPROVED** [review]
just fix the test and lint. then, it's ok for me.

**Comment by colmazia** [comment]
Does this have to be refactored with the new Bothan too?

**Comment by colmazia** [comment]
Should be converted to draft until updated and refactored to match the new bothan

**Comment by warittornc** [comment]
closing this PR for now as theres no defined timeline for it as of current

**Pull request closed without merging**
